# config.yml

one_wire:
  pin: GPIO4

sensors:
  temperature:
    - name: "Air Temperature"
      id: "28-3ce1e380151f"
    - name: "Soil Temperature"
      id: "28-3ce1e3801e12"
  wifi:
    update_interval: 60
